import React from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';
import { createStore } from 'redux';
import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import reducer from './reducers';
import App from './routes/App';

const initialState = {
  'user': {},
  'readBlog': {},
  'myBlog': [],
  'certificados': [
    {
      'id': 1,
      'title': 'MySQL y SQL',
      'year': 2020,
      'hour': 30,
      'png': 'https://github.com/dignelidxdx/PersonalPortfolio/blob/master/src/assets/static/diploma-sql-mysql-1.png?raw=true',
    },

    {
      'id': 2,
      'title': 'JAVA SE Avanzado',
      'year': 2020,
      'hour': 120,
      'png': 'https://github.com/dignelidxdx/PersonalPortfolio/blob/master/src/assets/static/diploma-java-avanzado-1.png?raw=true',
    },
    {
      'id': 3,
      'title': 'ReactJS',
      'year': 2020,
      'hour': 20,
      'png': 'https://github.com/dignelidxdx/PersonalPortfolio/blob/master/src/assets/static/diploma-react-ejs-1.png?raw=true',
    },
    {
      'id': 4,
      'title': 'Frontend Developer',
      'year': 2020,
      'hour': 50,
      'png': 'https://github.com/dignelidxdx/Portfolio/blob/master/src/assets/static/diploma-frontend-developer-1.png?raw=true',
    },
    {
      'id': 5,
      'title': 'Postman',
      'year': 2020,
      'hour': 6,
      'png': 'https://github.com/dignelidxdx/Portfolio/blob/master/src/assets/static/diploma-postman-1.png?raw=true',
    },
    {
      'id': 6,
      'title': 'Fundamento de Ing. de Software',
      'year': 2019,
      'hour': 16,
      'png': 'https://github.com/dignelidxdx/Portfolio/blob/master/src/assets/static/diploma-ingenieria-1.png?raw=true',
    },
    {
      'id': 7,
      'title': 'SCRUM',
      'year': 2019,
      'hour': 16,
      'png': 'https://github.com/dignelidxdx/Portfolio/blob/master/src/assets/static/diploma-scrum-1.png?raw=true',
    },
    {
      'id': 8,
      'title': 'Comunicación efectiva para equipos',
      'year': 2019,
      'hour': 8,
      'png': 'https://github.com/dignelidxdx/Portfolio/blob/master/src/assets/static/diploma-comunicacion-equipos-1.png?raw=true',
    },
    {
      'id': 9,
      'title': 'Arquitectura Backend',
      'year': 2021,
      'hour': 14,
      'png': 'https://github.com/dignelidxdx/PersonalPortfolio/blob/master/src/assets/static/diploma-practico-backend.png?raw=true',
    },
    {
      'id': 10,
      'title': 'Node.JS',
      'year': 2021,
      'hour': 21,
      'png': 'https://github.com/dignelidxdx/PersonalPortfolio/blob/master/src/assets/static/diploma-practico-node.png?raw=true',
    },
    {
      'id': 11,
      'title': 'PostgreSQL',
      'year': 2020,
      'hour': 15,
      'png': 'https://github.com/dignelidxdx/PersonalPortfolio/blob/master/src/assets/static/diploma-postgresql.png?raw=true',
    },
    {
      'id': 12,
      'title': 'Python',
      'year': 2021,
      'hour': 16,
      'png': 'https://github.com/dignelidxdx/PersonalPortfolio/blob/master/src/assets/static/diploma-python.png?raw=true',
    },
    {
      'id': 13,
      'title': 'Secure Coding',
      'year': 2021,
      'hour': 16,
      'png': 'https://github.com/dignelidxdx/PersonalPortfolio/blob/master/src/assets/static/Secure-Coding-OWASPTOP10.png?raw=true',
    },
  ],
  'blogs': [
    {
      'id': 1,
      'categoria': 'Travel',
      'img': 'https://github.com/dignelidxdx/PersonalPortfolio/blob/master/src/assets/static/marplata.jpg?raw=true',
      'title': 'Planificación para viajar fácil',
      'paragraph': 'Viajar es una de las cosas fundamentales para estar mentalmente saludables y para el corazón. Hay expertos que recomientan viajes 2 veces por año, ¿Porqué será tan importante?',
      'horasLectura': 10,
    },
    {
      'id': 2,
      'categoria': 'Diseño Web',
      'img': 'https://github.com/dignelidxdx/PersonalPortfolio/blob/master/src/assets/static/background-computer.jpg?raw=true',
      'title': '¿Cómo hago la maquetación?',
      'paragraph': 'A veces comenzar a maquetar es difícil, no solo sabiendo las bases, si no aprender varias librerías y saber que existen para llegar a maquetar de una forma muy dinámica y profesional. En este post te enseño HTML, CSS y varios links de librerías',
      'horasLectura': 10,
    },
    {
      'id': 3,
      'categoria': 'Backend',
      'img': 'https://github.com/dignelidxdx/PersonalPortfolio/blob/master/src/assets/static/portadas/javaBlog.png?raw=true',
      'title': 'Java, como mi lenguaje de programación',
      'paragraph': 'Java es un lenguaje de programación compilado en una serie de ByteCodes que nació en 1995 por Sun MicroSystem Java es rápido, portable, seguro y confiable con un lenguaje. Te contare de su historia y sistaxis, yo la amo! A pesar que es fuertemente typeado.',
      'horasLectura': 10,
    },
    {
      'id': 4,
      'categoria': 'Idiomas',
      'img': 'https://github.com/dignelidxdx/PersonalPortfolio/blob/master/src/assets/static/portadas/english.png?raw=true',
      'title': 'How (not) to learn english',
      'paragraph': "Are very intelligent people better at learning languages that average people? No, experts have shown that intelligence doesn't make a lot of differente. What makes the biggest difference is your attitude.",
      'horasLectura': 10,
    },
    {
      'id': 5,
      'categoria': 'Desarrollo Web',
      'img': 'https://github.com/dignelidxdx/PersonalPortfolio/blob/master/src/assets/static/portadas/POOBlog.png?raw=true',
      'title': 'Paradigmas de programación',
      'paragraph': 'Si hablamos de paradigmas en la programación podemos entender que es una forma de solucionar problemas por medio de creencias, prácticas y conocimientos que guian el desarrollo de una disciplina durante un período de tiempo. Acá podremos aprender cuales son los paradigmas más utilizados para resolver problemas.',
      'horasLectura': 10,
    },
    {
      'id': 6,
      'categoria': 'Soft Skill',
      'img': 'https://github.com/dignelidxdx/PersonalPortfolio/blob/master/src/assets/static/portadas/motivacion.png?raw=true',
      'title': 'Motivación',
      'paragraph': 'Se que muchos pensaran, todos tenemos motivación, hay veces que se nos hace dificil mantenerlo o saber identificarlo al momento, es ahí donde entra la disciplina. La motivación y la disciplina deberían trabajar a la mano, ya que una ayuda a potenciar el comienzo y la otra a mantener esa ruta hasta llegar a la meta.',
      'horasLectura': 10,
    },
    {
      'id': 7,
      'categoria': 'Bases de datos',
      'img': 'https://github.com/dignelidxdx/PersonalPortfolio/blob/master/src/assets/static/portadas/basesMysql.png?raw=true',
      'title': 'MySQL como base de datos relacional',
      'paragraph': 'Aquí comienza mi pasión por la tecnología, cuando conocí como estructuraban y recopilaban la información. MySQL es relacional ya que mantiene comunicación con otras tablas, las tablas podrian decirse que son un conjunto de registros y columnas con atributos que tienen diferentes tipos de datos.',
      'horasLectura': 10,
    },
    {
      'id': 8,
      'categoria': 'Fundamentos Informáticos',
      'img': 'https://github.com/dignelidxdx/PersonalPortfolio/blob/master/src/assets/static/portadas/bitbytesBlog.png?raw=true',
      'title': '¿Qué son Bit y Bytes?',
      'paragraph': 'Muchos dirán que el Byte es una unidad de información digital equivalente a 4 Bits, pero realmente que hay dentro de nuestro equipos. Sabías que los procesadores trabajan con Bytes determinados y que antes fabricar un CPU era bastante costoso. El Bit es la cantidad mas pequeña de datos, ya que representa la entrada y salida de la corriente: 0 y 1.',
      'horasLectura': 10,
    },
    {
      'id': 9,
      'categoria': 'Fundamentos Informáticos',
      'img': 'https://github.com/dignelidxdx/PersonalPortfolio/blob/master/src/assets/static/portadas/codigolimpio.png?raw=true',
      'title': 'Un resumen del código limpio y su significado',
      'paragraph': 'Nodejs es el backend de parte de javascript pero que tan diferente es de las sintaxis de Java, C++ o PHP.',
      'horasLectura': 10,
    },
    {
      'id': 10,
      'categoria': 'Fundamentos Informáticos',
      'img': 'https://github.com/dignelidxdx/PersonalPortfolio/blob/master/src/assets/static/portadas/documentacion.png?raw=true',
      'title': 'Importancia de la documentación del código',
      'paragraph': 'Nodejs es el backend de parte de javascript pero que tan diferente es de las sintaxis de Java, C++ o PHP.',
      'horasLectura': 10,
    },
    {
      'id': 11,
      'categoria': 'Frontend',
      'img': 'https://github.com/dignelidxdx/PersonalPortfolio/blob/master/src/assets/static/portadas/javascriptBlog.png?raw=true',
      'title': 'Javascript',
      'paragraph': 'Nodejs es el backend de parte de javascript pero que tan diferente es de las sintaxis de Java, C++ o PHP.',
      'horasLectura': 10,
    },
    {
      'id': 12,
      'categoria': 'Frontend',
      'img': 'https://github.com/dignelidxdx/PersonalPortfolio/blob/master/src/assets/static/portadas/proyectoReact.png?raw=true',
      'title': 'React.JS como librería',
      'paragraph': 'Nodejs es el backend de parte de javascript pero que tan diferente es de las sintaxis de Java, C++ o PHP.',
      'horasLectura': 10,
    },
    {
      'id': 13,
      'categoria': 'Soft Skills',
      'img': 'https://github.com/dignelidxdx/PersonalPortfolio/blob/master/src/assets/static/portadas/consumir.png?raw=true',
      'title': 'Para crear contenido hay que consumir',
      'paragraph': 'Nodejs es el backend de parte de javascript pero que tan diferente es de las sintaxis de Java, C++ o PHP.',
      'horasLectura': 10,
    },
    {
      'id': 14,
      'categoria': 'Diseño Web',
      'img': 'https://github.com/dignelidxdx/PersonalPortfolio/blob/master/src/assets/static/portadas/diseno.png?raw=true',
      'title': 'Sistema de Diseño ',
      'paragraph': 'Nodejs es el backend de parte de javascript pero que tan diferente es de las sintaxis de Java, C++ o PHP.',
      'horasLectura': 10,
    },
    {
      'id': 15,
      'categoria': 'Soft Skills',
      'img': 'https://github.com/dignelidxdx/PersonalPortfolio/blob/master/src/assets/static/portadas/habitos.png?raw=true',
      'title': 'Hábitos Atómicos',
      'paragraph': 'Nodejs es el backend de parte de javascript pero que tan diferente es de las sintaxis de Java, C++ o PHP.',
      'horasLectura': 10,
    },
    {
      'id': 16,
      'categoria': 'Backend',
      'img': 'https://github.com/dignelidxdx/PersonalPortfolio/blob/master/src/assets/static/portadas/pythonBlog.png?raw=true',
      'title': 'Python, como tu codigo de programación',
      'paragraph': 'Nodejs es el backend de parte de javascript pero que tan diferente es de las sintaxis de Java, C++ o PHP.',
      'horasLectura': 10,
    },
    {
      'id': 17,
      'categoria': 'Frontend',
      'img': 'https://github.com/dignelidxdx/PersonalPortfolio/blob/master/src/assets/static/portadas/reactjsBlog.png?raw=true',
      'title': 'Todo lo que hay que saber de React.JS',
      'paragraph': 'Nodejs es el backend de parte de javascript pero que tan diferente es de las sintaxis de Java, C++ o PHP.',
      'horasLectura': 10,
    },
    {
      'id': 18,
      'categoria': 'Fundamentos informáticos',
      'img': 'https://github.com/dignelidxdx/PersonalPortfolio/blob/master/src/assets/static/portadas/teoriaIngInformatica.jpg?raw=true',
      'title': 'Ingeniería Informática',
      'paragraph': 'Nodejs es el backend de parte de javascript pero que tan diferente es de las sintaxis de Java, C++ o PHP.',
      'horasLectura': 10,
    },
    {
      'id': 19,
      'categoria': 'Fundamentos informáticos',
      'img': 'https://github.com/dignelidxdx/PersonalPortfolio/blob/master/src/assets/static/portadas/teoriaIngSoftware.png?raw=true',
      'title': 'Ingeniería de Sofware',
      'paragraph': 'Nodejs es el backend de parte de javascript pero que tan diferente es de las sintaxis de Java, C++ o PHP.',
      'horasLectura': 10,
    },
    {
      'id': 20,
      'categoria': 'Fundamentos informáticos',
      'img': 'https://github.com/dignelidxdx/PersonalPortfolio/blob/master/src/assets/static/portadas/git-comand.png?raw=true',
      'title': 'Los comandos de GIT',
      'paragraph': 'Cuando iniciamos un proyecto es importante mantenerlo guardado o hacer backup pero sin perder su linea de tiempo. Porque... y si dañamos la versión actual? como recuperamos luego los cambios anteriores? Por eso es importante el uso de controles de versiones con git para tener cada paso del proyecto resguardado.',
      'horasLectura': 10,
      'titleSecond': 'Comandos Básicos',
      'codigo': 'git init',
      'codigoTwo': 'git commit -m "your first commit here"',
      'codigoThree': 'git remote add origin https://github.com/your-URL',
      'codigoFour': 'git push -u origin NombreDeBranch',
      'codigoFive': 'git help',
      'codigoFix': 'git pull origin NombreDeBranch',
      'paragraphSecond': 'Este comando ayuda a inicializar la repo local, con esta puedes comenzar a mantener versonada tu aplicación.',
      'titleThree': '',
      'paragraphThree': '',
      'titleFour': '',
      'paragraphFour': '',
      'titleFive': '',
      'paragraphFive': '',
      'titleSix': '',
      'paragraphSix': '',
      'titleSeven': '',
      'paragraphSeven': '',
    },
    {
      'id': 21,
      'categoria': 'Backend',
      'img': 'https://github.com/dignelidxdx/PersonalPortfolio/blob/master/src/assets/static/portadas/anotaciones.png?raw=true',
      'title': 'Las Anotaciones en JAVA',
      'paragraph': 'Las anotaciones (@) en java son muy utilizadas en el framework Springboot y estas ayudan a mapear los datos dentro de la base de datos relacionada en property. Támbien nos ayuda a guiarnos y que el código entienda la solución que queremos implementar.',
      'horasLectura': 10,
      'titleSecond': ' Patrón de Arquitectura MVC',
      'paragraphSecond': 'Ahora para entender un poco antes del patrón de diseño existe para separar lo que es la parte lógica y visual del negocio. Nos ayuda a tomar una mejor nomenclatura y entender mejor lo que codeamos, es como una manera de categorizar. Se compone por 3 componentes: modelo, vista y controlador. Ahora bien, doy esta explicación para ir por parte y entender las anotaciones.',
      'titleThree': '',
      'paragraphThree': '',
      'titleFour': '',
      'paragraphFour': '',
      'titleFive': '',
      'paragraphFive': '',
      'titleSix': '',
      'paragraphSix': '',
      'titleSeven': '',
      'paragraphSeven': '',
    },
  ],
  'trends': [
    {
      'id': 2,
      'slug': 'tvshow-2',
      'title': 'In the Dark',
      'type': 'Scripted',
      'language': 'English',
      'year': 2009,
      'contentRating': '16+',
      'duration': 164,
      'cover': 'http://dummyimage.com/800x600.png/99118E/ffffff',
      'description': 'Vestibulum ac est lacinia nisi venenatis tristique',
      'source': 'https://mdstrm.com/video/58333e214ad055d208427db5.mp4',
    },
    {
      'id': 3,
      'slug': 'tvshow-3',
      'title': 'Instinct',
      'type': 'Adventure',
      'language': 'English',
      'year': 2002,
      'contentRating': '16+',
      'duration': 137,
      'cover': 'http://dummyimage.com/800x600.png/302140/ffffff',
      'description': 'Vestibulum ac est lacinia nisi venenatis tristique',
      'source': 'https://mdstrm.com/video/58333e214ad055d208427db5.mp4',
    },
    {
      'id': 4,
      'slug': 'tvshow-4',
      'title': 'Grand Hotel',
      'type': 'Comedy',
      'language': 'English',
      'year': 2014,
      'contentRating': '16+',
      'duration': 163,
      'cover': 'http://dummyimage.com/800x600.png/5472FF/ffffff',
      'description': 'Vestibulum ac est lacinia nisi venenatis tristique',
      'source': 'https://mdstrm.com/video/58333e214ad055d208427db5.mp4',
    },
    {
      'id': 5,
      'slug': 'tvshow-5',
      'title': 'Stargate Atlantis',
      'type': 'Scripted',
      'language': 'English',
      'year': 2014,
      'contentRating': '16+',
      'duration': 194,
      'cover': 'http://dummyimage.com/800x600.png/B36F20/ffffff',
      'description': 'Vestibulum ac est lacinia nisi venenatis tristique',
      'source': 'https://mdstrm.com/video/58333e214ad055d208427db5.mp4',
    },
    {
      'id': 6,
      'slug': 'tvshow-6',
      'title': 'Final Space',
      'type': 'Scripted',
      'language': 'English',
      'year': 2017,
      'contentRating': '16+',
      'duration': 124,
      'cover': 'http://dummyimage.com/800x600.png/CCC539/ffffff',
      'description': 'Vestibulum ac est lacinia nisi venenatis tristique',
      'source': 'https://mdstrm.com/video/58333e214ad055d208427db5.mp4',
    },
    {
      'id': 7,
      'slug': 'tvshow-7',
      'title': 'The InBetween',
      'type': 'Drama',
      'language': 'English',
      'year': 2011,
      'contentRating': '16+',
      'duration': 179,
      'cover': 'http://dummyimage.com/800x600.png/FF7A90/ffffff',
      'description': 'Vestibulum ac est lacinia nisi venenatis tristique',
      'source': 'https://mdstrm.com/video/58333e214ad055d208427db5.mp4',
    },
  ],
  'originals': [
    {
      'id': 8,
      'slug': 'tvshow-8',
      'title': 'Stargate Atlantis',
      'type': 'Action',
      'language': 'English',
      'year': 2012,
      'contentRating': '16+',
      'duration': 148,
      'cover': 'http://dummyimage.com/800x600.png/306880/ffffff',
      'description': 'Vestibulum ac est lacinia nisi venenatis tristique',
      'source': 'https://mdstrm.com/video/58333e214ad055d208427db5.mp4',
    },
    {
      'id': 9,
      'slug': 'tvshow-9',
      'title': 'Alien Highway',
      'type': 'Action',
      'language': 'English',
      'year': 2019,
      'contentRating': '16+',
      'duration': 128,
      'cover': 'http://dummyimage.com/800x600.png/604180/ffffff',
      'description': 'Vestibulum ac est lacinia nisi venenatis tristique',
      'source': 'https://mdstrm.com/video/58333e214ad055d208427db5.mp4',
    },
    {
      'id': 10,
      'slug': 'tvshow-10',
      'title': 'Elementary',
      'type': 'Animation',
      'language': 'English',
      'year': 2011,
      'contentRating': '16+',
      'duration': 346,
      'cover': 'http://dummyimage.com/800x600.png/FF91BA/ffffff',
      'description': 'Vestibulum ac est lacinia nisi venenatis tristique',
      'source': 'https://mdstrm.com/video/58333e214ad055d208427db5.mp4',
    },
    {
      'id': 11,
      'slug': 'tvshow-11',
      'title': 'Strange Angel',
      'type': 'War',
      'language': 'English',
      'year': 2015,
      'contentRating': '16+',
      'duration': 226,
      'cover': 'http://dummyimage.com/800x600.png/45807C/ffffff',
      'description': 'Vestibulum ac est lacinia nisi venenatis tristique',
      'source': 'https://mdstrm.com/video/58333e214ad055d208427db5.mp4',
    },
    {
      'id': 12,
      'slug': 'tvshow-12',
      'title': 'Private Eyes',
      'type': 'Comedy',
      'language': 'English',
      'year': 2018,
      'contentRating': '16+',
      'duration': 190,
      'cover': 'http://dummyimage.com/800x600.png/577380/ffffff',
      'description': 'Vestibulum ac est lacinia nisi venenatis tristique',
      'source': 'https://mdstrm.com/video/58333e214ad055d208427db5.mp4',
    },
    {
      'id': 13,
      'slug': 'tvshow-13',
      'title': 'NCIS: Los Angeles',
      'type': 'Drama',
      'language': 'English',
      'year': 2010,
      'contentRating': '16+',
      'duration': 160,
      'cover': 'http://dummyimage.com/800x600.png/5472FF/ffffff',
      'description': 'Vestibulum ac est lacinia nisi venenatis tristique',
      'source': 'https://mdstrm.com/video/58333e214ad055d208427db5.mp4',
    },
  ],
};

const store = createStore(reducer, initialState);

ReactDOM.render(
  <Provider store={store}>
    <App />
  </Provider>,
  document.getElementById('app'),
);
